
# Name of the DDM class that will be used as a simulator.
simulator: 
  _target_: ddm_stride.ddm_models.basic_ddm.BasicDDM

# Specify parameters theta that will be used for inference.
# Choose a proposal/prior distribution from torch.distributions or utils.distributions.
parameters:
- name: drift
  distribution: 
    _target_: torch.distributions.uniform.Uniform
    low: -2
    high: 2
- name: boundary_separation
  distribution: 
    _target_: torch.distributions.uniform.Uniform
    low: 0.5
    high: 2
- name: starting_point
  distribution:
    _target_: torch.distributions.uniform.Uniform
    low: 0.3
    high: 0.7

# Input values contain additional values pi used for simulating that no inference will be performed on.
# Choose a proposal distribution from torch.distributions or utils.distributions.
experimental_conditions:

# Observations x specify results of the simulator.
observations:
- name: choice
  variable_type: discrete
- name: rt
  variable_type: continuous
