
# Name of the DDM class that will be used as a simulator.
simulator: 
  _target_: ddm_stride.ddm_models.base_simulator.Simulator

# Specify parameters theta that will be used for inference.
# Choose a proposal/prior distribution from torch.distributions or utils.distributions.
parameters:
- name:
  distribution: 
    _target_:
    # add distribution arguments

# Input values contain additional values pi used for simulating that no inference will be performed on.
# Choose a proposal distribution from torch.distributions or utils.distributions.
experimental_conditions:
- name:
  distribution:
    _target_:
    # add distribution arguments

# Observations x specify results of the simulator.
observations:
- name:
  variable_type: