
# Name of the DDM class that will be used as a simulator.
simulator: 
  _target_: ddm_stride.ddm_models.full_ddm.FullDDM
# Specify parameters theta that will be used for inference.
# Choose a proposal/prior distribution from torch.distributions or utils.distributions.
parameters:
- name: drift
  distribution: 
    _target_: 
- name: boundary_separation
  distribution: 
    _target_: 
- name: starting_point
  distribution: 
    _target_: 
- name: non_decision_time
  distribution: 
    _target_: 
- name: atv_drift
  distribution: 
    _target_: torch.distributions.uniform.Uniform
    low: 0
    high: 2.5 
- name: atv_starting_point
  distribution: 
    _target_: torch.distributions.uniform.Uniform
    low: 0
    high: 0.5
- name: atv_non_decision_time
  distribution:
    _target_: torch.distributions.uniform.Uniform
    low: 0
    high: 0.3

# Input values contain additional values pi used for simulating that no inference will be performed on.
# Choose a proposal distribution from torch.distributions or utils.distributions.
experimental_conditions:

# Observations x specify results of the simulator.
observations:
- name: choice
  variable_type: discrete
- name: rt
  variable_type: continuous
